name: CI

on:
  push:
    branches: [main, master]
  pull_request:

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: pytest -q

  arch:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - uses: actions/checkout@v3
      - name: Install system packages
        run: pacman -Sy --noconfirm python python-pip git
      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt
      - name: Run tests
        run: pytest -q
